version: '3.8'
services:
  frontend:
    build:
      context: ./health-insurance-planner-frontend
    # Add any other configuration specific to your frontend service
    ports:
      - 3001:3000

  backend:
    build:
      context: ./health-insurance-planner-backend
    # Add any other configuration specific to your backend service
    ports:
      - '5001:5000'
    environment:
      - PORT=5000

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27020:27017'
    volumes:
    - mongodb_data:/data/db

volumes:
  mongodb_data: